"""Persistence boundary for project membership, immutable sources and acceptance leases."""
from typing import Protocol


class DeveloperRepository(Protocol):
    async def projects(self, actor: str, admin: bool) -> list[dict]: ...
    async def project(self, project_id: str) -> dict: ...
    async def create_project(self, body: dict, actor: str) -> dict: ...
    async def update_project(self, project_id: str, body: dict, actor: str) -> dict: ...
    async def versions(self, project_id: str) -> list[dict]: ...
    async def version(self, version_id: str, package: bool = False) -> dict: ...
    async def create_version(self, project_id: str, actor: str, body: dict, raw: bytes, manifest: dict, digest: str) -> dict: ...
    async def retry(self, version_id: str, actor: str, *, internal_worker: bool = False) -> dict: ...
    async def claim(self) -> dict | None: ...
    async def update_version(self, version_id: str, lease: str, values: dict) -> dict: ...
    async def release(self, version_id: str, actor: str, expected_revision: str, *, internal_worker: bool = False) -> dict: ...
    async def heartbeat(self, value: dict) -> None: ...
    async def status(self) -> dict: ...
