"""Persistence contract for module management and the local release queue."""
from typing import Any, Protocol


class ModuleRepository(Protocol):
    async def policy(self, module_id: str) -> dict[str, Any]: ...
    async def save_policy(self, module_id: str, policy: dict, actor: str) -> dict: ...
    async def seed(self, module_id: str, policy: dict) -> None: ...
    async def record_check(self, actor: str, result: dict) -> dict: ...
    async def checks(self) -> list[dict]: ...
    async def create_job(self, actor: str, body: dict) -> dict: ...
    async def jobs(self) -> list[dict]: ...
    async def approve(self, job_id: str, actor: str) -> dict: ...
    async def claim(self) -> dict | None: ...
    async def update_job(self, job_id: str, lease: str, update: dict) -> dict: ...
