"""Durable workflow drafts, published snapshots and execution receipts."""
from __future__ import annotations

from typing import Protocol


class ModuleFlowRepository(Protocol):
    async def list(self) -> list[dict]: ...
    async def get(self, workflow_id: str, *, published: bool = False) -> dict: ...
    async def save(self, draft: dict, actor: str) -> dict: ...
    async def publish(self, workflow_id: str, revision: int, definition: dict, actor: str) -> dict: ...
    async def unpublish(self, workflow_id: str, revision: int, actor: str) -> dict: ...
    async def begin_run(self, workflow_id: str, revision: int, actor: str, request_id: str, digest: str, mode: str) -> tuple[dict, bool]: ...
    async def update_run(self, run: dict) -> dict: ...
    async def runs(self, workflow_id: str, actor: str | None = None) -> list[dict]: ...
